/mavros/**:
  ros__parameters:
    plugin_denylist:
      - adsb
      - cam_imu_sync
      - camera
      - cellular_status
      - cmd
      - companion_process
      - debug_value
      - distance_sensor
      - esc_status
      - esc_telemetry
      - fake_gps
      - ftp
      - global_position
      - gps_input
      - gps_rtk
      - gpsstatus
      - guided_target
      - hil
      - home_position
      # - imu
      - landing_target
      - local_position
      - log_transfer
      - mag_calibration
      - manual_control
      - mavros
      - mavros_node
      - mavros_router
      - mission
      - mocap
      - mount_control
      - nav_controller_output
      - obstacle
      - odometry
      - onboard_computer
      - optical_flow
      - param
      - play_tune
      - px4flow
      - rallypoint
      - rangefinder
      - rc
      - setpoint_accel
      - setpoint_attitude
      - setpoint_position
      - setpoint_raw
      - setpoint_trajectory
      - setpoint_velocity
      - sys
      - tdr_radio
      - terrain
      - time
      - trajectory
      - transform_listener_impl_aaaab713dbf8
      - tunnel
      - vfr_hud
      - vibration
      - vision_pose
      - vision_speed
      - wheel_odometry
      - wind

    # plugin_allowlist:

